// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7POMIvAz1mN7_ZyQ2zcuL_UD8-NSDvU',
    appId: '1:240261600858:web:0c8a58b6403dccb7296a63',
    messagingSenderId: '240261600858',
    projectId: 'football-ticket-7dd30',
    authDomain: 'football-ticket-7dd30.firebaseapp.com',
    storageBucket: 'football-ticket-7dd30.firebasestorage.app',
    measurementId: 'G-B350NX1G7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5KHJNQQvQ0DO9X159rda3T0TGX-k4Lo',
    appId: '1:240261600858:android:42c1b433c0146eec296a63',
    messagingSenderId: '240261600858',
    projectId: 'football-ticket-7dd30',
    storageBucket: 'football-ticket-7dd30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8p4UwxWO4JnfAXVrYI4gtLEPQexkQFBc',
    appId: '1:240261600858:ios:29e17db66b8da600296a63',
    messagingSenderId: '240261600858',
    projectId: 'football-ticket-7dd30',
    storageBucket: 'football-ticket-7dd30.firebasestorage.app',
    iosClientId: '240261600858-9qfrafi7l72lmom4p1kjtfn7n342btj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballTicket',
  );
}
